
defaults:
  - _self_
  - cluster/local
  - override hydra/sweeper: SMAC

hydra:
  sweeper:
    smac_class: smac.facade.blackbox_facade.BlackBoxFacade
    scenario:
      seed: 42
      n_trials: 100
      deterministic: true
      n_workers: 4
    smac_kwargs:
      dask_client:
        _target_: dask.distributed.Client
        address: ${create_cluster:${cluster},${hydra.sweeper.scenario.n_workers}}
      logging_level: 20  # 10 DEBUG, 20 INFO
    search_space:  # TODO adjust search space
      hyperparameters:
        x0:
          type: uniform_float
          lower: -5
          upper: 10
          log: false
        x1:
          type: uniform_float
          lower: 0
          upper: 15
          log: false
          default_value: 2
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}

x0: 3
x1: 4

seed: None
budget: None  # TODO document if used: add this to config

spurious_var: 3.14